language: python

python:
- '2.7'

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_b7014b0dabac_key -iv $encrypted_b7014b0dabac_iv -in id_rsa_personal.enc -out ~/.ssh/id_rsa_personal -d
- chmod 400 ~/.ssh/id_rsa_personal

install:
- pip install ansible

jobs:
  include:
  - stage: deploy-staging
    script: ansible-playbook -i ansible/inventory.staging.yml ansible/playbook.yml --user $ANSIBLE_USER --private-key ~/.ssh/id_rsa_personal
