- hosts: all
  tasks:
    - name: Install git
      become: yes
      apt:
        name: git
        state: present

    - name: Install ruby
      become: yes
      apt:
        name: ruby
        state: present

    - name: Install sinatra
      become: yes
      shell: gem install sinatra

    - name: Clean up existing app
      shell: rm -rf travis-ansible

    - name: Download app
      shell: git clone https://github.com/ecojuntak/travis-ansible.git

    - name: Copy service file
      become: yes
      shell: cp travis-ansible/ruby-app.service /etc/systemd/system

    - name: Run app
      become: yes
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: ruby-app
